local utils = require('gtodo-md.utils')

describe("utils.is_todo_line", function()
  it("should return true for todo lines", function()
    assert.is_true(utils.is_todo_line("- [ ] This is a task"))
    assert.is_true(utils.is_todo_line("  - [ ] Indented task"))
    assert.is_true(utils.is_todo_line("[ ] Task without dash"))
    assert.is_true(utils.is_todo_line("- [ ]"))
  end)

  it("should return false for done lines", function()
    assert.is_false(utils.is_todo_line("- [x] Done task"))
    assert.is_false(utils.is_todo_line("  - [X] Done task uppercase"))
    assert.is_false(utils.is_todo_line("[x] Done task without dash"))
  end)

  it("should return false for non-task lines", function()
    assert.is_false(utils.is_todo_line("Just a normal text line"))
    assert.is_false(utils.is_todo_line("- List item but not a task"))
    assert.is_false(utils.is_todo_line(""))
    assert.is_false(utils.is_todo_line(nil))
  end)
end)

describe("utils.is_done_line", function()
  it("should return true for done lines", function()
    assert.is_true(utils.is_done_line("- [x] Done task"))
    assert.is_true(utils.is_done_line("  - [x] Indented done task"))
    assert.is_true(utils.is_done_line("- [X] Uppercase done task"))
    assert.is_true(utils.is_done_line("[x] Done task without dash"))
  end)

  it("should return false for todo lines", function()
    assert.is_false(utils.is_done_line("- [ ] Todo task"))
    assert.is_false(utils.is_done_line("  - [ ] Indented todo task"))
    assert.is_false(utils.is_done_line("[ ] Todo task without dash"))
  end)

  it("should return false for non-task lines", function()
    assert.is_false(utils.is_done_line("Just a normal text line"))
    assert.is_false(utils.is_done_line("- List item but not a task"))
    assert.is_false(utils.is_done_line(""))
    assert.is_false(utils.is_done_line(nil))
  end)
end)
